FROM node:latest as build-stage

RUN mkdir -p /app

WORKDIR /app

COPY . /app

RUN npm install

ENV NODE_ENV=production

RUN npm run build


FROM nginx:latest as production-stage

RUN rm -rf /usr/share/nginx/html/*

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

COPY --from=build-stage /app/dist .

EXPOSE 5010

CMD ["nginx", "-g", "daemon off;"]